name = "discord_luau/rest"
version = "0.0.1"
description = "Discord-Luau Rest - providing calls to the discord HTTP Rest API"
license = "MIT"
authors = ["AsyncMatrix<https://github.com/4x8Matrix>"]
repository = "https://github.com/DiscordLuau/discord-luau"
pesde_version = "0.5.2"

includes = ["src/**", "pesde.toml", "LICENSE"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
std_polyfills = { workspace = "discord_luau/std_polyfills" }
api_types = { workspace = "discord_luau/api_types" }
future = { name = "yetanotherclown/luau_futures", target = "luau", version = "2.0.0-beta.3" }
