# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
lune = "filiptibell/lune@0.8.0"
stylua = "JohnnyMorganz/StyLua@0.20.0"
selene = "Kampfkarren/selene@0.27.1"
moonwave = "evaera/moonwave@1.1.2"