name = "discord_luau/std_polyfills"
version = "0.0.1"
description = "Discord-Luau Polyfills - polyfills for stdlib functions."
license = "MIT"
authors = ["AsyncMatrix<https://github.com/4x8Matrix>"]
repository = "https://github.com/DiscordLuau/discord-luau"
pesde_version = "0.5.2"

includes = ["src/**", "pesde.toml", "LICENSE"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"