name = "discord_luau/builders"
version = "0.0.1"
description = "Discord-Luau Builders - Builders used to generate payloads that the discord API can parse."
license = "MIT"
authors = ["AsyncMatrix <catbob614@gmail.com>"]
repository = "https://github.com/DiscordLuau/discord-luau"
pesde_version = "0.5.2"

includes = ["src/**", "pesde.toml", "LICENSE"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
std_polyfills = { workspace = "discord_luau/std_polyfills" }
api_types = { workspace = "discord_luau/api_types" }
util = { workspace = "discord_luau/util" }
bit = { workspace = "discord_luau/bit", target = "luau" }