name = "discord_luau/api_types"
version = "0.0.1"
description = "Discord-Luau Types - API Types for the Discord API."
license = "MIT"
authors = ["AsyncMatrix <catbob614@gmail.com>"]
repository = "https://github.com/DiscordLuau/discord-luau"
pesde_version = "0.5.2"

includes = ["src/**", "pesde.toml", "LICENSE"]

[target]
environment = "lune"
lib = "bundled.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
util = { workspace = "discord_luau/util" }
bit = { workspace = "discord_luau/bit", target = "luau" }