name = "discord_luau/buffer"
version = "0.0.1"
description = "Discord-Luau Buffer - Used to temporarily storing encoded data."
license = "MIT"
authors = ["AsyncMatrix <catbob614@gmail.com>"]
repository = "https://github.com/DiscordLuau/discord-luau"
pesde_version = "0.5.2"

includes = ["src/**", "pesde.toml", "LICENSE"]

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"