name = "discord_luau/emitter"
version = "0.0.1"
description = "Discord-Luau Emitter - A signal-like alternative for luau"
license = "MIT"
authors = ["AsyncMatrix<https://github.com/4x8Matrix>"]
repository = "https://github.com/DiscordLuau/discord-luau"
pesde_version = "0.5.2"

includes = ["src/**", "pesde.toml", "LICENSE"]

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"