name = "discord_luau/state"
version = "0.0.1"
description = "Discord-Luau State - contains the state for a discord bot."
license = "MIT"
authors = ["AsyncMatrix<https://github.com/4x8Matrix>"]
repository = "https://github.com/DiscordLuau/discord-luau"
pesde_version = "0.5.2"

includes = ["src/**", "pesde.toml", "LICENSE"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
std_polyfills = { workspace = "discord_luau/std_polyfills" }
api_types = { workspace = "discord_luau/api_types" }
websocket = { workspace = "discord_luau/websocket" }
rest = { workspace = "discord_luau/rest" }
secret = { workspace = "discord_luau/secret", target = "luau" }